<a href="https://colab.research.google.com/github/dechl-98/etl-data-pipeline-2534532021/blob/main/notebook/C_pagos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_67zv_user:TV9HLZks2Q2TRRYt42vPETVOyKIcAYx2@dpg-d6qu70shg0os73b4gfj0-a.oregon-postgres.render.com/etl_seguros_67zv"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 17.5 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [2]:
import pandas as pd

url = "https://raw.githubusercontent.com/dechl-98/etl-data-pipeline-2534532021/refs/heads/main/data/raw/C_pagos.csv"

df = pd.read_csv(url)

df.head()

  id_pago id_venta         metodo monto_pagado
0  PG8000    V9057  Transferencia      4452.68
1  PG8001    V9027  Transferencia      1742.47
2  PG8002    V9025        Tarjeta       789.21
3  PG8003    V9112  Transferencia       146.73
4  PG8004    V9190       Efectivo       3236.2

In [3]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_pago       246 non-null    object
 1   id_venta      239 non-null    object
 2   metodo        246 non-null    object
 3   monto_pagado  236 non-null    object
dtypes: object(4)
memory usage: 7.8+ KB

id_pago          0
id_venta         7
metodo           0
monto_pagado    10
dtype: int64

In [4]:
df.columns = df.columns.str.strip().str.lower()

for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].astype(str).str.strip()

df = df.replace(r'^\s*$', pd.NA, regex=True)

df = df.drop_duplicates()

print('df after processing:')
display(df.head())

print('\nInfo about df:')
df.info()

df after processing:

  id_pago id_venta         metodo monto_pagado
0  PG8000    V9057  Transferencia      4452.68
1  PG8001    V9027  Transferencia      1742.47
2  PG8002    V9025        Tarjeta       789.21
3  PG8003    V9112  Transferencia       146.73
4  PG8004    V9190       Efectivo       3236.2

Info about df:
<class 'pandas.core.frame.DataFrame'>
Index: 240 entries, 0 to 239
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_pago       240 non-null    object
 1   id_venta      240 non-null    object
 2   metodo        240 non-null    object
 3   monto_pagado  240 non-null    object
dtypes: object(4)
memory usage: 9.4+ KB

In [5]:
validos = df[
    df['id_pago'].notna() &
    df['monto_pagado'].notna()
].copy()

rechazados = df[
    df['id_pago'].isna() |
    df['monto_pagado'].isna()
].copy()

print('Valid Payments (validos):')
display(validos.head())

print('\nRejected Payments (rechazados):')
display(rechazados.head())

Valid Payments (validos):

  id_pago id_venta         metodo monto_pagado
0  PG8000    V9057  Transferencia      4452.68
1  PG8001    V9027  Transferencia      1742.47
2  PG8002    V9025        Tarjeta       789.21
3  PG8003    V9112  Transferencia       146.73
4  PG8004    V9190       Efectivo       3236.2

Rejected Payments (rechazados):

Empty DataFrame
Columns: [id_pago, id_venta, metodo, monto_pagado]
Index: []

In [6]:
def motivo(row):
    motivos = []
    if pd.isna(row['id_pago']):
        motivos.append("id_pago_vacio")
    if pd.isna(row['monto_pagado']):
        motivos.append("monto_pagado_vacio")
    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

print('Rejected Payments (rechazados) with rejection reason:')
display(rechazados.head())

Rejected Payments (rechazados) with rejection reason:

Empty DataFrame
Columns: [id_pago, id_venta, metodo, monto_pagado, motivo_rechazo]
Index: []

In [7]:
validos.to_csv("pagos_curated.csv", index=False)
rechazados.to_csv("pagos_rejects.csv", index=False)
print("DataFrames saved to CSV files.")
!mkdir -p data/curated
!mkdir -p data/rejects

!mv pagos_curated.csv data/curated/pagos_curated.csv
!mv pagos_rejects.csv data/rejects/pagos_rejects.csv

print("CSV files moved to their respective directories.")

DataFrames saved to CSV files.
CSV files moved to their respective directories.

In [8]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_67zv_user:TV9HLZks2Q2TRRYt42vPETVOyKIcAYx2@dpg-d6qu70shg0os73b4gfj0-a.oregon-postgres.render.com/etl_seguros_67zv"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
   ?column?
0         1

In [9]:
validos.to_sql(
    'pagos_curated',
    engine,
    if_exists='append',
    index=False
)
print("Valid payments uploaded to 'pagos_curated' table.")

rechazados.to_sql(
    'pagos_rejects',
    engine,
    if_exists='append',
    index=False
)
print("Rejected payments uploaded to 'pagos_rejects' table.")

Valid payments uploaded to 'pagos_curated' table.
Rejected payments uploaded to 'pagos_rejects' table.

In [10]:
pd.read_sql(
"SELECT * FROM pagos_curated LIMIT 10",
engine
)

  id_pago id_venta         metodo monto_pagado
0  PG8000    V9057  Transferencia      4452.68
1  PG8001    V9027  Transferencia      1742.47
2  PG8002    V9025        Tarjeta       789.21
3  PG8003    V9112  Transferencia       146.73
4  PG8004    V9190       Efectivo       3236.2
5  PG8005    V9065         Cheque      3191.77
6  PG8006    V9152         Cheque      1716.21
7  PG8007    V9130     Pago móvil       377.13
8  PG8008    V9199       Efectivo      2059.95
9  PG8009    V9043  Transferencia      1569.86