<a href="https://colab.research.google.com/github/dechl-98/etl-data-pipeline-2534532021/blob/main/notebook/C_ventas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_67zv_user:TV9HLZks2Q2TRRYt42vPETVOyKIcAYx2@dpg-d6qu70shg0os73b4gfj0-a.oregon-postgres.render.com/etl_seguros_67zv"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 30.8 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [2]:
import pandas as pd

url = "https://raw.githubusercontent.com/dechl-98/etl-data-pipeline-2534532021/refs/heads/main/data/raw/C_ventas.csv"

df = pd.read_csv(url)

df.head()

  id_venta id_cliente       fecha    total
0    V9000      CL154  2024-10-25  4641.86
1    V9001      CL243  2024-06-29  1138.59
2    V9002      CL111  2024-01-25  1873.39
3    V9003      CL244  2024-01-26      NaN
4    V9004      CL243  2024-05-24  2208.24

In [3]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_venta    248 non-null    object
 1   id_cliente  242 non-null    object
 2   fecha       239 non-null    object
 3   total       241 non-null    object
dtypes: object(4)
memory usage: 7.9+ KB

id_venta      0
id_cliente    6
fecha         9
total         7
dtype: int64

In [4]:
df.columns = df.columns.str.strip().str.lower()

for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].astype(str).str.strip()

df = df.replace(r'^\s*$', pd.NA, regex=True)

df = df.drop_duplicates()

print('df after processing:')
display(df.head())

print('\nInfo about df:')
df.info()

df after processing:

  id_venta id_cliente       fecha    total
0    V9000      CL154  2024-10-25  4641.86
1    V9001      CL243  2024-06-29  1138.59
2    V9002      CL111  2024-01-25  1873.39
3    V9003      CL244  2024-01-26      nan
4    V9004      CL243  2024-05-24  2208.24

Info about df:
<class 'pandas.core.frame.DataFrame'>
Index: 240 entries, 0 to 239
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_venta    240 non-null    object
 1   id_cliente  240 non-null    object
 2   fecha       240 non-null    object
 3   total       240 non-null    object
dtypes: object(4)
memory usage: 9.4+ KB

In [5]:
valid_sales = df[
    df['id_venta'].notna() &
    df['total'].notna()
].copy()

rejected_sales = df[
    df['id_venta'].isna() |
    df['total'].isna()
].copy()

print('Valid Sales (valid_sales):')
display(valid_sales.head())

print('\nRejected Sales (rejected_sales):')
display(rejected_sales.head())

Valid Sales (valid_sales):

  id_venta id_cliente       fecha    total
0    V9000      CL154  2024-10-25  4641.86
1    V9001      CL243  2024-06-29  1138.59
2    V9002      CL111  2024-01-25  1873.39
3    V9003      CL244  2024-01-26      nan
4    V9004      CL243  2024-05-24  2208.24

Rejected Sales (rejected_sales):

Empty DataFrame
Columns: [id_venta, id_cliente, fecha, total]
Index: []

In [6]:
def get_rejection_reason(row):
    reasons = []
    if pd.isna(row['id_venta']):
        reasons.append("id_venta_vacio")
    if pd.isna(row['total']):
        reasons.append("total_vacio")
    return ",".join(reasons)

rejected_sales["rejection_reason"] = rejected_sales.apply(get_rejection_reason, axis=1)

print('Rejected Sales (rejected_sales) with rejection reason:')
display(rejected_sales.head())

Rejected Sales (rejected_sales) with rejection reason:

Empty DataFrame
Columns: [id_venta, id_cliente, fecha, total, rejection_reason]
Index: []

In [7]:
valid_sales.to_csv("sales_curated.csv", index=False)
rejected_sales.to_csv("sales_rejects.csv", index=False)
print("DataFrames saved to CSV files.")
!mkdir -p data/curated
!mkdir -p data/rejects
!mv sales_curated.csv data/curated/sales_curated.csv
!mv sales_rejects.csv data/rejects/sales_rejects.csv

print("CSV files moved to their respective directories.")

DataFrames saved to CSV files.
CSV files moved to their respective directories.

In [8]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_67zv_user:TV9HLZks2Q2TRRYt42vPETVOyKIcAYx2@dpg-d6qu70shg0os73b4gfj0-a.oregon-postgres.render.com/etl_seguros_67zv"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
   ?column?
0         1

In [9]:
valid_sales.to_sql(
    'sales_curated',
    engine,
    if_exists='append',
    index=False
)
print("Valid sales uploaded to 'sales_curated' table.")

rejected_sales.to_sql(
    'sales_rejects',
    engine,
    if_exists='append',
    index=False
)
print("Rejected sales uploaded to 'sales_rejects' table.")

Valid sales uploaded to 'sales_curated' table.
Rejected sales uploaded to 'sales_rejects' table.

In [10]:
pd.read_sql(
"SELECT * FROM sales_curated LIMIT 10",
engine
)

  id_venta id_cliente       fecha    total
0    V9000      CL154  2024-10-25  4641.86
1    V9001      CL243  2024-06-29  1138.59
2    V9002      CL111  2024-01-25  1873.39
3    V9003      CL244  2024-01-26      nan
4    V9004      CL243  2024-05-24  2208.24
5    V9005      CL239  2024-09-10  3072.44
6    V9006      CL235  2024-11-01  4716.52
7    V9007      CL102  2025-03-07  1218.65
8    V9008      CL243  2024-11-30   625.08
9    V9009      CL129  2024-12-10   1003.4